### ISSUE TITLE
Progress Bar issue

### ISSUE THREAD

**Issue by KOs0s** [Wolfy024/Renamer-Bot#7]
The bot get's stuck at 'initiating progress bar' and not just that /rename doesn't work either,

see if you can fix that problem, love your work <3

**Comment by KOs0s** [comment]
> The bot get's stuck at 'initiating progress bar' and not just that /rename doesn't work either,
> 
> see if you can fix that problem, love your work <3

**Comment by Wolfy024** [comment]
Ok, could you further elaborate. The bot works absolutely fine for me.  Are you sure you read the help commands correctly ? if yes, then is your heroku dyno not finished ? If this is not the case, send me a pic on @Itadori_Yuji_San on telegram...

**Comment by Wolfy024** [comment]
and maybe if there is a bug, I can fix it. Otherwise, I can help you sort out.
